# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e141767a3ea024e4393ba9d60f38e32a7ece75aa3a4064109c04a25088690a678a9e5a8d04ce922729aa9227e0b8257f673245552d265c8d841b3b01ec0b97b0

test:
  secret_key_base: 6da293ca67ae5df34c35ee75e0572d266d2463ba0164f687146bbc96c3feb919b9826122903ad0c4304d91ca7f2008cf34fade02e77234b5fdabfa76b8317cc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
